CREATE TABLE AUTHOR
(
  ID   INT PRIMARY KEY NOT NULL,
  NAME CHAR(500)       NOT NULL
);
CREATE TABLE ALBUM
(
  ID        INT PRIMARY KEY NOT NULL,
  NAME      CHAR(500)       NOT NULL,
  GENRE     CHAR(500),
  AUTHOR_ID INT REFERENCES AUTHOR (ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE SONG
(
  ID       INT PRIMARY KEY NOT NULL,
  NAME     CHAR(500)       NOT NULL,
  DURATION INT,
  ALBUM_ID INT REFERENCES ALBUM (ID) ON DELETE CASCADE ON UPDATE CASCADE
);